name: 'Cache pip and poetry'
description: 'Cache pip and poetry for GitHub Actions'
runs:
    using: 'composite'
    steps:
        - name: 'Cache pip'
          shell: bash
          uses: actions/cache@v3
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: 'Cache poetry'
          shell: bash
          uses: actions/cache@v3
          with:
            path: ~/.cache/pypoetry
            key: ${{ runner.os }}-pypoetry-${{ hashFiles('**/poetry.lock') }}
            restore-keys: |
              ${{ runner.os }}-pypoetry-
