version: "3.9"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"

services:
    sfs.local:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: poetry run app
        volumes:
            - ./src:/app/src
        depends_on:
            - minio.local
        ports:
            - "1995:${APP_DEFAULT_PORT}"
        env_file:
            - dotenv/app.env
        logging: *logging

    minio.local:
        image: minio/minio:latest
        restart: always
        command: server --console-address ":${STORAGE_CONSOLE_PORT}" /data
        environment:
            MINIO_ROOT_USER: "${STORAGE_ROOT_USER}"
            MINIO_ROOT_PASSWORD: "${STORAGE_ROOT_PASSWORD}"
        ports:
            - "${STORAGE_API_PORT}:${STORAGE_API_PORT}"
            - "${STORAGE_CONSOLE_PORT}:${STORAGE_CONSOLE_PORT}"
        volumes:
            - minio_storage:/data
        env_file:
            - dotenv/storage.env
        logging: *logging

volumes:
    minio_storage:
