version: "3.9"

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "3"

services:
    sfs.local:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        command: poetry run app
        depends_on:
            - mongo.local
            - minio.local
        volumes:
            - ./src:/app/src
        logging: *logging

    minio.local:
        image: minio/minio:RELEASE.2024-10-13T13-34-11Z
        restart: always
        environment:
            MINIO_ROOT_USER: "${STORAGE_ROOT_USER}"
            MINIO_ROOT_PASSWORD: "${STORAGE_ROOT_PASSWORD}"
            MINIO_ACCESS_KEY: "${STORAGE_ACCESS_KEY}"
            MINIO_SECRET_KEY: "${STORAGE_SECRET_KEY}"
            MINIO_REGION_NAME: "${STORAGE_REGION_NAME:-af-south-1}"
        healthcheck:
            test: [ "CMD", "mc", "ready", "local" ]
            interval: 5s
            timeout: 5s
            retries: 5
        command: server --console-address ":${STORAGE_API_PORT}" /data
        volumes:
            - minio_storage:/data
        logging: *logging

    mongo.local:
        image: mongo:7.0.12
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
        volumes:
            - sfs_data:/data/db
        logging: *logging

networks:
    sfs_network:
        driver: bridge

volumes:
    sfs_data:
    minio_storage:
        driver: local
